# prep
FROM node:lts-alpine as prep
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build

# production
FROM nginx:stable-alpine as production
COPY nginx_default.conf /etc/nginx/conf.d/default.conf
COPY --from=prep /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
