# prep
FROM node:lts-alpine as prep
WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn stage

# production
FROM nginx:stable-alpine as production
COPY --from=prep /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
